/*
  Warnings:

  - You are about to drop the `FUNCIOANRIO` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE `FUNCIOANRIO` DROP FOREIGN KEY `FUNCIOANRIO_ID_PERFIL_fkey`;

-- DropTable
DROP TABLE `FUNCIOANRIO`;

-- CreateTable
CREATE TABLE `FUNCIONARIO` (
    `id_funcionario` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_PERFIL` INTEGER NOT NULL,
    `NOME` VARCHAR(250) NOT NULL,
    `EMAIL` VARCHAR(60) NOT NULL,
    `SENHA` VARCHAR(100) NOT NULL,
    `TELEFONE` VARCHAR(15) NOT NULL,
    `STATUS` BOOLEAN NOT NULL,

    UNIQUE INDEX `FUNCIONARIO_EMAIL_key`(`EMAIL`),
    PRIMARY KEY (`id_funcionario`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `FUNCIONARIO` ADD CONSTRAINT `FUNCIONARIO_ID_PERFIL_fkey` FOREIGN KEY (`ID_PERFIL`) REFERENCES `PERFIL`(`ID_PERFIL`) ON DELETE RESTRICT ON UPDATE CASCADE;
