-- CreateTable
CREATE TABLE `FUNCIOANRIO` (
    `id_funcionario` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_PERFIL` INTEGER NOT NULL,
    `NOME` VARCHAR(250) NOT NULL,
    `EMAIL` VARCHAR(60) NOT NULL,
    `SENHA` VARCHAR(100) NOT NULL,
    `TELEFONE` VARCHAR(15) NOT NULL,
    `STATUS` BOOLEAN NOT NULL,

    UNIQUE INDEX `FUNCIOANRIO_EMAIL_key`(`EMAIL`),
    PRIMARY KEY (`id_funcionario`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PERFIL` (
    `ID_PERFIL` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(300) NOT NULL,

    PRIMARY KEY (`ID_PERFIL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `FUNCIOANRIO` ADD CONSTRAINT `FUNCIOANRIO_ID_PERFIL_fkey` FOREIGN KEY (`ID_PERFIL`) REFERENCES `PERFIL`(`ID_PERFIL`) ON DELETE RESTRICT ON UPDATE CASCADE;
